steps:
# build
- name: 'node'
  entrypoint: 'npm'
  args:
  - ci
# test
- name: 'node'
  entrypoint: 'npm'
  args:
  - test
# decrypt the secrets (Grrr! https://issuetracker.google.com/issues/124468298)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - -c
  - |
    echo 'Checking if master branch...'
    if [[ "$BRANCH_NAME" == "master" ]]; then
      echo 'Checking if tagged version'
      echo "Also worth inspecting TAG_NAME: $TAG_NAME"
      if git describe --exact-match HEAD; then
        gcloud kms decrypt --ciphertext-file=.env.enc --plaintext-file=.env \
          --location=global --keyring=aws-agent --key=aws-agent || true
      fi
    fi
# deploy if tagged
- name: 'node'
  entrypoint: bash
  args:
  - -c
  - |
    echo 'Checking if master branch...'
    if [[ "$BRANCH_NAME" == "master" ]]; then
      echo 'Checking if tagged version'
      if git describe --exact-match HEAD; then
        make publish-all
      fi
    fi
