name: publish
on:
  push:
    branches: [ main ]
    paths:
      - 'lib/manifest.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        npm ci
        make package-all

    - uses: kewisch/action-web-ext@d5376aebf5a5f167924728cf9b43d6e9e8ee10e0
      with:
        cmd: sign
        source: firefox.zip
        channel: listed
        apiKey: ${{ secrets.AMO_SIGN_KEY }}
        apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
        timeout: 900000

    - uses: trmcnvn/chrome-addon@3431bca72e30167ac2c2266100b8198615ef37e3
      with:
        zip: chrome.zip
        extension: jjgjefclcmpfpoiinpkpbdllboockoia
        client-id: ${{ secrets.CWS_CLIENT_ID }}
        client-secret: ${{ secrets.CWS_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CWS_REFRESH_TOKEN }}

    - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: firefox.zip chrome.zip
