name: version bumper
on:
  push:
    branches: [ main ]
    paths:
      - 'package-lock.json'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: phips28/gh-action-bump-version@fbcc304011575d00305d09602e85766d7d3fd7a5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix: v
